### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by laheller** [abrudana/wwa#1]
Was there a NuGet package created from WWA library and published to nuget.org?

**Comment by abrudana** [comment]
No, there wasn't.

**Comment by laheller** [comment]
@abrudana I see your first name is Attila. Are you hungarian? If yes, can we chat somewhere?
I have some questions regarding to this library.

**Comment by abrudana** [comment]
@laheller yes I am Hungarian! :)
Sure we can chat. Please find me on Skype.

**Comment by laheller** [comment]
Since there is already a [nuget package](https://www.nuget.org/packages/WWA/), this issue can be closed.
