### ISSUE TITLE
Remove the merge tags from code

### ISSUE THREAD

**Issue by rpawlaszek** [abrudana/wwa#2]
Hi @abrudana, I see that the current code in master has merge conflicts tags pushed with the source (e.g. [ab.cs](https://github.com/abrudana/wwa/commit/0805b7297f007122b376a2ce659173836f3a7f1d#diff-ea67b2e6b449b029f0d7c4fc00066d58)). Could I ask you to finalize the merge? 

Thanks in advance!
Rafal

**Comment by abrudana** [comment]
Hi Rafal,
Cannot see any conflicts. Would you please help me to find it?
Regards,
Attila

**Comment by rpawlaszek** [comment]
Hi @abrudana, as I see there are the git conflict markers e.g. [here](https://github.com/abrudana/wwa/blob/master/WorldWideAstronomy/WWA/Astronomy/Astrometry/ab.cs) committed in the cs files.

**Comment by abrudana** [comment]
Ok, I got it. You are right.
Unfortunately every c# files have conflicts. :( Do not like GIT.

**Comment by rpawlaszek** [comment]
@abrudana haha, you wrote it on **Git**Hub;)

**Comment by abrudana** [comment]
Fixed!
Thanx for your help!
Best regards.

**Comment by rpawlaszek** [comment]
Thank you very much.

**Comment by abrudana** [comment]
I hosted it on GITHub 'cause Codeplex closed down... :(
