### ISSUE TITLE
Missing NuGet package build

### ISSUE THREAD

**Issue by papaathome** [abrudana/wwa#4]
Dear Sir,

Thank you kindly for providing a wrapper in C# for the SOFA package.
It gives me a flying start in my C# projects.

I have one suggestion to make, can you add some code for generating NuGet packages for WWA.dll?
I have tested it on the package I'm using at the moment and it is strait forward to do.
As an example I added a zip file (WWA-8.diff.zip) with all the changed/added files, implementing by you should be as simple as merging in those files.

I made the changes on code from a file wwa-8.zip with the following note in it.
Current WWA Library release based on :  SOFA Library Issue 2017-04-20 for ANSI C

During my testing I made the following notes: (also included in the .zip file)
Quote: Changelog.md
TODO:
On WWA nuget packages:
- Check if it is allowed to redistribute nuget.exe
- Decide on WWA.nuspec configuration settings.
- Decide on distributing a NuGet package or not.

Done:
20190226:
- SOFA: given windows SDK not available: upgraded fom windows SDK version 10.0.10586.0 to 10.0.16299.0
- WWA: added WWA.nuspec. (for general specs see: "https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package")
- WWA: added post processing command "nuget.exe pack $(ProjectDir)$(ProjectFileName) -Prop Configuration=$(ConfigurationName)"
- WWA: build WWA.14.0.0-beta.nupkg and put it in my local repository.
- WWATest: removed the direct reference to project WWA output (WWA.dll)
- WWATest: Added a reference to NuGetPackage WWA.14.0.0-beta.nupkg from my local repository.
- WWATest: build and executed WWATest.exe, positive result.

Note 1a:
To use nuget.exe
a) install it in a location that is available in %PATH%
b) use it in the post processing command with a path to nuget.exe
I have opted for a)

Note 1b:
To set up a local NuGet repository.
- Create a directory dedocated for local nuget pagkages.
- Open the NuGet Settings dialog via Tools > NuGet Package Manager > Package Manager Settings.
  Click the Package Sources tab within the settings dialog, followed by the ‘plus’ icon in the top left to add a new package source.

Note 2:
It is easier to have two project files in one directory, using all the same source files.
There is one `but', it is not possible to mix .NETFramwork and .NETCore projects in one directory.
(I have tested with a .NETCore project and can build a NuGet package from that, but only from a separate directory.)
Unquote
[WWA-8.diff.zip](https://github.com/abrudana/wwa/files/2912215/WWA-8.diff.zip)

**Comment by laheller** [comment]
Yep, a nuget package of this library would be great!

**Comment by abrudana** [comment]
Dear @papaathome ,
Thank you for your time to create code for NuGet package.
As soon as I have time implemented it.
Thank you very much!
Regards.

**Comment by papaathome** [comment]
Dear Sir,

Any time you need. In the mean time, people should be able to create a NuGet Package with the notes and zip file I supplied.
If you have any questions or want something tested/clarified, please do not hesitate to call me.

Oh, and my name is André.

Kind regards,

**Comment by papaathome** [comment]
> 
> 
> Yep, a nuget package of this library would be great!

Have a look in the zip file, you find a NuGet package in "WWA-8.diff.zip\WorldWideAstronomy\packages\WWA.14.0.0-beta\WWA.14.0.0-beta.nupkg".
See if you can use it and keep us informed of your findings. But keep in mind, it is a beta version.

Kind regards,

**Comment by abrudana** [comment]
Dear André,
I would like to learn how to create NuGet package by my self (I never did it before). Your comments are very helpful.

Thany you!
Regards.

**Comment by abrudana** [comment]
WWA is now available as a NuGet package!
👍 :)

**Comment by laheller** [comment]
Cool!
Király! 🥇 😃

**Comment by papaathome** [comment]
Great! 
Unfortunately, I'm not able to test it tonight. Other appointments.
But I will at some other time this weekend.

Kind regards,
Andre.

**Comment by papaathome** [comment]
I was able to pull the WWA NuGet package from NuGet.org but using it will have to wait.
Gread job. I like it.

Kind regards,
André.
