### ISSUE TITLE
Self documentation of static wwa* method names

### ISSUE THREAD

**Issue by laheller** [abrudana/wwa#6]
Hi @abrudana 

One more thing for this library would be really useful:
Adding [self documentation](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc) to this library, at least a [summary](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/summary) to static method names, since they are quite meaningless.
I mean for example the method _WorldWideAstronomy.WWA.wwaA2af( )_
might have this description:

```
/// <summary>
/// decompose radians into degrees, arcminutes, arcseconds
/// </summary>
public static void wwaA2af(int ndp, double angle, ref char sign, int[] idmsf) {
	wwaD2tf(ndp, angle * 2.3873241463784303, ref sign, idmsf);
}
```

To get the correct summary description for each method name I would use SOFA library document:
http://www.iausofa.org/2018_0130_C/sofa/manual.lis

**Comment by abrudana** [comment]
Hi @laheller (Laci),
Every method has < summary >, < remarks > and < param > docs.

![image](https://user-images.githubusercontent.com/6791058/53629283-79f74380-3c0d-11e9-9e9b-73e576f2b8cd.png)

![image](https://user-images.githubusercontent.com/6791058/53629308-84b1d880-3c0d-11e9-96be-3c9dd6fdf75d.png)

![image](https://user-images.githubusercontent.com/6791058/53629322-8e3b4080-3c0d-11e9-97de-e3a22becbf8d.png)

Regards,
Attila

**Comment by laheller** [comment]
As we figured out, the generated XML documentation is missing from nuget package.

TIP: Add link to nuget package in **README.MD**.

**Comment by abrudana** [comment]
New package published!
Version: 2018.1.30.2
Please try it!
Thanx & regards!
Attila

**Comment by papaathome** [comment]
Downloaded the new package and tested for the documentation.
No problems, it works for me. (in VS and in ILSpy)

Kind regards,
André.

![capture](https://user-images.githubusercontent.com/6624189/53679979-bcd01e80-3cd4-11e9-9254-6af8fc19383f.PNG)

![untitled](https://user-images.githubusercontent.com/6624189/53680029-8cd54b00-3cd5-11e9-87f8-dc64d472a441.png)
